ip="0.0.0.0"
port=10086
buffer_size=10240
max_size=524288000
max_files=3

[recorder]
logger_name="msgbag_recorder"
log_file="recorder.log"

[player]
logger_name="msgbag_player"
log_file="player.log"

